const StoreActionTypes = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS:'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE:'FETCH_COLLECTION_FAILURE',
  FETCH_PEOPLE_START:'FETCH_PEOPLE_START',
  FETCH_PEOPLE_SUCCESS:'FETCH_PEOPLE_SUCCESS',
  FETCH_PEOPLE_FAILURE:'FETCH_PEOPLE_FAILURE'
};

export default StoreActionTypes;